server {
    listen 4200;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: Proxy API requests if needed, though usually handled by API Gateway
    # location /api/ {
    #     proxy_pass http://api-gateway:8080/;
    # }
}
