### Creates a new customer entity
POST http://localhost:4004/api/customers
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "name": "Said Rahid",
  "email": "Said.rahid@gmail.com",
  "address": "Avenue Hassan II, Casablanca  ",
  "dateOfBirth": "2000-03-15",
  "registeredDate": "2024-11-15"
}

###