### Creates a new customer entity
POST http://localhost:4000/customers
Content-Type: application/json

{
  "name": "Mohammed Alami",
  "email": "mohammed.alami@gmail.com",
  "address": "Avenue Hassan II, Casablanca",
  "dateOfBirth": "1985-03-15"
}

###